### PR TITLE
Fix/tests

### PR DESCRIPTION
**Pull request by merryman**
Fixes the currently broken tests.

### CODE REVIEW

**Comment by linusha** [comment]
This hints at a bunch of stuff to think about, imo:

1. In CI, the test for the fixed proportional layout failed (see https://github.com/LivelyKernel/lively.next/actions/runs/7397667571). Locally, this was not the case for me. I adapted it now to match the one for the moving layout (which imo makes a lot more sense in general?) and now it seems to work both locally for me and in CI (https://github.com/LivelyKernel/lively.next/actions/runs/7398040068). The we have a situation where tests inconsistently fail between our local machines and CI sucks tremendously of course, however, as long as "only" graphical representation is concerned here I am willing to put this under "known issues"^^
2. The `startAndStopTicking` test is still flaky for me (just something I noticed while working on this).
3. The "http file listing contains properties of resource" test appears to be flaky (https://github.com/LivelyKernel/lively.next/actions/runs/7398040068/attempts/1).
4. I suspect that #1042 caused these, or do you have another culprit in mind? This once again raises the questions of running tests for each PR. We already discussed the idea of running the tests for all touched packages. As you rightly objected at that time, this will not catch all cases, as a lot of the core deps heavily rely on each other. However, as far as I can see, this would have helped us already in this case! Another option could be to only trigger the test running action once an approving review has been submitted, as a "last check" before merging.

Most of these discussions can be moved somewhere else. Please let me know if you agree with my changes to the tests and then I will merge this.

**Comment by merryman** [comment]
> This hints at a bunch of stuff to think about, imo:
> 
>     1. In CI, the test for the fixed proportional layout failed (see https://github.com/LivelyKernel/lively.next/actions/runs/7397667571). Locally, this was not the case for me. I adapted it now to match the one for the moving layout (which imo makes a lot more sense in general?) and now it seems to work both locally for me and in CI (https://github.com/LivelyKernel/lively.next/actions/runs/7398040068). The we have a situation where tests inconsistently fail between our local machines and CI sucks tremendously of course, however, as long as "only" graphical representation is concerned here I am willing to put this under "known issues"^^
✅
>     2. The `startAndStopTicking` test is still flaky for me (just something I noticed while working on this).
Agree, but lets handle this in a separate PR.
>     3. The "http file listing contains properties of resource" test appears to be flaky (https://github.com/LivelyKernel/lively.next/actions/runs/7398040068/attempts/1).
Same as above.
>     4. I suspect that [Fix/reconciliation #1042](https://github.com/LivelyKernel/lively.next/pull/1042) caused these, or do you have another culprit in mind? This once again raises the questions of running tests for each PR. We already discussed the idea of running the tests for all touched packages. As you rightly objected at that time, this will not catch all cases, as a lot of the core deps heavily rely on each other. However, as far as I can see, this would have helped us already in this case! Another option could be to only trigger the test running action once an approving review has been submitted, as a "last check" before merging.
No, the culprit here was definitely #625.
> 
> Most of these discussions can be moved somewhere else. Please let me know if you agree with my changes to the tests and then I will merge this.

**Comment by linusha** [comment]
> No, the culprit here was definitely #625.

Ah, this one I must have overlooked when going through the list of merged PRs! My point regarding the possible solutions for a more resilient CI check still stand though, I think. Thoughts @merryman?

**Review by linusha — APPROVED** [review]

**Comment by merryman** [comment]
> > No, the culprit here was definitely #625.
> 
> Ah, this one I must have overlooked when going through the list of merged PRs! My point regarding the possible solutions for a more resilient CI check still stand though, I think. Thoughts @merryman?

Yes with regards to the basic "check affected packages test", I would vouch for giving it a try. Go ahead and prepare a action which does the job and lets see how it goes.

**Pull request merged**
