### PR TITLE
📦: bump required nodejs version in install.sh + start.sh

### PR DESCRIPTION
**Pull request by merryman**
Should capture the issue that was *again* encountered in #561.

@linusha We may need to update the GitHub Actions stuff as well inside this PR.

### CODE REVIEW

**Comment by linusha** [comment]
I find the whole situation to be a bit confusing, to be honest.

I am quite sure that I was able to reproduce the situation Rick had as well, with an error occurring when running `start.sh`, but with `install.sh` succeeding. However, I did not take note of which node version I used to reproduce this. Just running `nvm use 17` gives me `17.9.1` and no problems.

Note, that the actions work as intended as well, and they run build processes (even running `install.sh` runs build processes nowadays!) with node version `17.8.x` for the most part.
Also, the offending line in the traces Rick provided (and they are consistent with what I observed) is line 16 in 52ef511157e536cbf5dfa6075654a977015d45f9 (the safe navigation `?.` syntax). That has been there for months. Why does it fail now? 

This is all quite curious, but in the end probably nothing we can reconstruct. I just wanted to point that out, so that we know what to look out for in the future, if something similar would happen again. It would be beneficial to understand what went wrong here, in order to add a CI check against this problem.

I just went ahead and specified the latest LTS version of `node` in the README, and will change all actions to use that as well.

Feel free to merge after reading this :smile:.

**Review by linusha — APPROVED** [review]

**Comment by merryman** [comment]
> I find the whole situation to be a bit confusing, to be honest.
> 
> 
> 
> I am quite sure that I was able to reproduce the situation Rick had as well, with an error occurring when running `start.sh`, but with `install.sh` succeeding. However, I did not take note of which node version I used to reproduce this. Just running `nvm use 17` gives me `17.9.1` and no problems.
> 
> 
> 
> Note, that the actions work as intended as well, and they run build processes (even running `install.sh` runs build processes nowadays!) with node version `17.8.x` for the most part.
> 
> Also, the offending line in the traces Rick provided (and they are consistent with what I observed) is line 16 in 52ef511157e536cbf5dfa6075654a977015d45f9 (the safe navigation `?.` syntax). That has been there for months. Why does it fail now? 
> 
> 
> 
> This is all quite curious, but in the end probably nothing we can reconstruct. I just wanted to point that out, so that we know what to look out for in the future, if something similar would happen again. It would be beneficial to understand what went wrong here, in order to add a CI check against this problem.
> 
> 
> 
> I just went ahead and specified the latest LTS version of `node` in the README, and will change all actions to use that as well.
> 
> 
> 
> Feel free to merge after reading this :smile:.

If that is the case we should not merge this. My understanding was this was solely due to a feature that node 18 supports and we implicitly now assume.
We should review in more detail what's really going on.

**Comment by merryman** [comment]
From the conversation in #561 it appears this has less to do with the nodejs version after all. I will close this for now.

**Comment by linusha** [comment]
> From the conversation in #561 it appears this has less to do with the nodejs version after all. I will close this for now.

Even though #561 is not the cause, I still think we should proceed with this. My two cents:

`node` 17 will not be a LTS version, sticking with that is thus at least bad practice. I am quite sure that we cannot go back to 16, the reason being something with esm support I believe? In the case it helps you remembering, here are some relevant commits:
image
 
This leaves us with 18 being the next LTS version we can use. Ironically, you were the first using 18, which is why we have `--no-experimental-fetch` in `install.sh`. Once we are on a LTS version again, we should begin to better document our version bumps. If nothing comes up that requires a newer version, LTS versions receive patches for 30 months.

What we could think about is if we introduce `--no-experimental-fetch` consistently before merging this, and/or looking into retiring `node-fetch` from `flatn`, which the implementation that now comes with node per default is based on.

**Comment by merryman** [comment]
Added an additional nodejs version check into the `install.sh` itself. That would have prevented rick form running into the issue he previously reported in #561.

**Pull request merged**
