### PR TITLE
Enhancement/improve freezer logging

### LINKED ISSUE #508: Fix build script logging
Currently the logging of the build scripts is quite messy and looks like it crashes during build (even when it runs through successfult). We need to:
 - Introduce proper logging info that is formatted accordingly
 - Also make the script return the correct value upon completion.

### PR DESCRIPTION
**Pull request by merryman**
Resolves #508. I am still figuring out a setup to see if the solution that triggers the exit code on a crash is working.

### CODE REVIEW

**Comment by merryman** [comment]
@linusha As far as my investigation goes we cannot control the exit codes of node.js from within the lively rollup plugin, at least not in the version `2.70` we are using right now. That means we need to adjust our custom build scripts to wrap rollup inside a `try {} catch` block and manually exit the process with the appropriate exit code. Not elegant, but since we generate these scripts most of the time anyways I guess its fair? Another thing we could look into is to upgrade to newer versions of rollup which handles errors and warnings in a more centralized fashion, however that I would do in a separate ticket. I remember that being a little tricky though since a bunch of things have changed between version 2 and 4.

**Review by linusha — CHANGES_REQUESTED** [review]
Overall, this looks goo to me.
I could confirm that the exit code works as expected.

Two questions/requests:

1. I still see the `browserslist`/`caniuse` output in the log, despite you removing that dependency. They are still somewhere in our dependency chain, resulting in 
```
rowserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```
Even deleting the node modules did not work, as `install.sh` will happily download them again.
Is this intended? Can we silence that similar to the async/await transpilation?

2. You introduced a verbose config option for the freezer plugin. Can we make that one easily accesible, at least in the bundling scripts for projects? One easy solution I can think of would be to just provide two `npm run` targets, like `npm run build` and `npm run build-verbose` or something. I am open to alternatives. What do you think?

**Comment by linusha** [comment]
@merryman As this is part of our current sprint, please also add time tracking information.

**Comment by merryman** [comment]
> Overall, this looks goo to me. I could confirm that the exit code works as expected.
> 
> Two questions/requests:
> 
>     1. I still see the `browserslist`/`caniuse` output in the log, despite you removing that dependency. They are still somewhere in our dependency chain, resulting in
> 
> 
> ```
> rowserslist: caniuse-lite is outdated. Please run:
> npx browserslist@latest --update-db
> ```
> 
> Even deleting the node modules did not work, as `install.sh` will happily download them again. Is this intended? Can we silence that similar to the async/await transpilation?

Yes, I think they are somehow imported via babel. I think we wont get rid of them unless we rid ourselves from babel, which will happen with #316. 
> 
>     2. You introduced a verbose config option for the freezer plugin. Can we make that one easily accesible, at least in the bundling scripts for projects? One easy solution I can think of would be to just provide two `npm run` targets, like `npm run build` and `npm run build-verbose` or something. I am open to alternatives. What do you think?

I would prefer a flag, but I can add that to the scripts, yes!

**Comment by merryman** [comment]
> > I would prefer a flag, but I can add that to the scripts, yes!
> 
> Works for me! For future reference: We can then later on control this flag via #1223.

Added the verbose flag now, please review!

**Pull request merged**
