### PR TITLE
🧰: add debug console

### PR DESCRIPTION
**Pull request by merryman**
Carries over the previous parts based implementation of Console into a component based definition.

### CODE REVIEW

**Review by linusha — CHANGES_REQUESTED** [review]
1. This is a cool tool!
2. I propose we should bring at least the world command to open this tool up back, would you agree?
3. I would like to have comments here, as the workings of this tool are not super straight forward. If that is okay with you, I'd like to add them myself and have you review them, to make sure I understood correctly what is going on here. Just leave me a comment if that works for you...
4. To me this seems to be only a "half way" usage of the `ViewModel` architecture? I think I would like to get rid of the `LocalJSConsole` subclass of `Text` and move the functionality into the `ViewModel`. Or am I missing something? 
I think this also causes problems functionality wise as it is, as I am not able to invoke the static `open` method, as thus unable to open the Console in a window?
If you agree and give green ligh, I will take care of this together with the comments, @merryman.

**Comment by merryman** [comment]
> 1. This is a cool tool!
> 2. I propose we should bring at least the world command to open this tool up back, would you agree?
> 3. I would like to have comments here, as the workings of this tool are not super straight forward. If that is okay with you, I'd like to add them myself and have you review them, to make sure I understood correctly what is going on here. Just leave me a comment if that works for you...
> 4. To me this seems to be only a "half way" usage of the `ViewModel` architecture? I think I would like to get rid of the `LocalJSConsole` subclass of `Text` and move the functionality into the `ViewModel`. Or am I missing something?
>    I think this also causes problems functionality wise as it is, as I am not able to invoke the static `open` method, as thus unable to open the Console in a window?
>    If you agree and give green ligh, I will take care of this together with the comments, @merryman.

Agree to all of the above. Maybe should have turned this into a draft anyway. Feel free to add in your suggestions!

**Comment by linusha** [comment]
> Agree to all of the above. Maybe should have turned this into a draft anyway. Feel free to add in your suggestions!

Done :slightly_smiling_face: 

> That is correct but I ran into issues with the current implementation of view models which somewhat does not work well when we want to extend properties that are defined in the view already. In this case we want to extend the keybindings and commands property, which is already defined on the text itself. However there is no convenient way right now to easily extend those from the view model. We always end up loosing the what is defined on the text morph already...

I see, that makes sense. I experimented a bit with this and have implemented an attempt with `withoutBindingsDo()` which I thought should work (if it would be a nice solution is another matter) but it doesn't. I feel like I have a conceptual misunderstanding there of how some things with the `bindings` work, probably something for a call as well :telephone_receiver:

**Comment by merryman** [comment]
> > Agree to all of the above. Maybe should have turned this into a draft anyway. Feel free to add in your suggestions!
> 
> Done 🙂
> 
> > That is correct but I ran into issues with the current implementation of view models which somewhat does not work well when we want to extend properties that are defined in the view already. In this case we want to extend the keybindings and commands property, which is already defined on the text itself. However there is no convenient way right now to easily extend those from the view model. We always end up loosing the what is defined on the text morph already...
> 
> I see, that makes sense. I experimented a bit with this and have implemented an attempt with `withoutBindingsDo()` which I thought should work (if it would be a nice solution is another matter) but it doesn't. I feel like I have a conceptual misunderstanding there of how some things with the `bindings` work, probably something for a call as well 📞
> 
> @merryman If you are fine with my changes just leave me a comment or something, I will then approve and merge.

Yes let's talk about it. but overall all of this looks decent to me for the time being.

**Review by linusha — APPROVED** [review]

**Pull request merged**
